# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myfamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.TextField()),
                ('description', models.TextField(default='nice child')),
            ],
        ),
    ]
